force-app/main/default/objects/Vehicles__c/fields/KM_Driven__c.field-meta.xml
<CustomField>
    <fullName>KM_Driven__c</fullName>
    <label>KM_Driven</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/make__c.field-meta.xml
<CustomField>
    <fullName>make__c</fullName>
    <label>make</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <label>model</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/registration_date_earliest__c.field-meta.xml
<CustomField>
    <fullName>registration_date_earliest__c</fullName>
    <label>registration date earliest</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/registration_date_latest__c.field-meta.xml
<CustomField>
    <fullName>registration_date_latest__c</fullName>
    <label>registration date latest</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/testCazooVehicleController.cls
/**
 * @description       : 
 * @author            : Sudhir Kumar Thanna
 * @group             : 
 * @last modified on  : 11-02-2021
 * @last modified by  : Sudhir Kumar Thanna
**/
@IsTest
public with sharing class testCazooVehicleController {
   
    @IsTest
    public static void testGetGroupedData()
    {
        List<Vehicles__c> vhs = TestDataFactory1.createVehiclesData();
        Test.startTest();   
        cazooVehicleController.getGroupedData();
        Test.stopTest();
        List<AggregateResult> vehiclesGroupedList = [SELECT make__c,model__c,count(Name),SUM(KM_Driven__c),SUM(Revenue__c),registration_date_earliest__c,registration_date_latest__c
                                                     FROM Vehicles__c GROUP BY make__c,model__c,registration_date_earliest__c,registration_date_latest__c];
        System.assertEquals(4, vehiclesGroupedList.size());      
    }

    @IsTest
    public static void testGetGroupedData_nullCase()
    {
        Test.startTest();   
        cazooVehicleController.getGroupedData();
        Test.stopTest();
        List<AggregateResult> vehiclesGroupedList = [SELECT make__c,model__c,count(Name),SUM(KM_Driven__c),SUM(Revenue__c),registration_date_earliest__c,registration_date_latest__c
                                                     FROM Vehicles__c GROUP BY make__c,model__c,registration_date_earliest__c,registration_date_latest__c];
        System.assertEquals(0, vehiclesGroupedList.size());      
    }

    @IsTest
    public static void testGetGroupedDataByQuery()
    {
        List<Vehicles__c> vhs = TestDataFactory1.createVehiclesData();
        Test.startTest();   
        cazooVehicleController.getGroupedDataByQuery('BMW','720d');
        Test.stopTest();
        List<Vehicles__c> vehiclesList = [SELECT Id,make__c,model__c,registration_date_earliest__c,registration_date_latest__c 
                                            FROM Vehicles__c
                                            WHERE make__c='BMW' AND model__c='720d'];
        System.assertEquals(2, vehiclesList.size());      
    }

    @IsTest
    public static void testGetGroupedDataByQuery_nullCase()
    {
        List<Vehicles__c> vhs = TestDataFactory1.createVehiclesData();
        Test.startTest();   
        cazooVehicleController.getGroupedDataByQuery('XYZ','ABC');
        Test.stopTest();
        List<Vehicles__c> vehiclesList = [SELECT Id,make__c,model__c,registration_date_earliest__c,registration_date_latest__c 
                                            FROM Vehicles__c
                                            WHERE make__c='XYZ' AND model__c='ABC'];
        System.assertEquals(0, vehiclesList.size());      
    }
}