force-app/main/default/objects/Vehicles__c/fields/KM_Driven__c.field-meta.xml
<CustomField>
    <fullName>KM_Driven__c</fullName>
    <label>KM_Driven</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/make__c.field-meta.xml
<CustomField>
    <fullName>make__c</fullName>
    <label>make</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <label>model</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/registration_date_earliest__c.field-meta.xml
<CustomField>
    <fullName>registration_date_earliest__c</fullName>
    <label>registration date earliest</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/registration_date_latest__c.field-meta.xml
<CustomField>
    <fullName>registration_date_latest__c</fullName>
    <label>registration date latest</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/cazooVehicleController.cls
/**
 * @description       : 
 * @author            : Sudhir Kumar Thanna
 * @group             : 
 * @last modified on  : 11-02-2021
 * @last modified by  : Sudhir Kumar Thanna
**/
public with sharing class cazooVehicleController {

    /**
    * @description 
    * @author Sudhir Kumar Thanna | 11-02-2021 
    * @return List<AggregateResult> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getGroupedData(){
        List<AggregateResult> vehiclesGroupedList = [SELECT make__c,model__c,count(Name),SUM(KM_Driven__c),SUM(Revenue__c),registration_date_earliest__c,registration_date_latest__c FROM Vehicles__c GROUP BY make__c,model__c,registration_date_earliest__c,registration_date_latest__c];
        if(vehiclesGroupedList.size()>0){
            return vehiclesGroupedList;
        }
        return null;
    }

    /**
    * @description 
    * @author Sudhir Kumar Thanna | 11-02-2021 
    * @param make 
    * @param model 
    * @return List<AggregateResult> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getGroupedDataByQuery(String make, String model){
        List<AggregateResult> vehiclesGroupedQueryList = [SELECT make__c,model__c,count(Name),SUM(KM_Driven__c),SUM(Revenue__c),registration_date_earliest__c,registration_date_latest__c FROM Vehicles__c 
                                                        WHERE make__c=:make AND model__c=:model
                                                        GROUP BY make__c,model__c,registration_date_earliest__c,registration_date_latest__c ];
        if(vehiclesGroupedQueryList.size()>0){
            return vehiclesGroupedQueryList;
        }
        return null;
    }
}